# registratin form using tkinter
from tkinter import *
from tkinter import messagebox
win=Tk()
win.title("registration form")
win.geometry("400x400")
win.maxsize(400,400)
win.minsize(400,400)
win.config(bg="red")
l1=Label(win,text="name")
l1.grid(row=0,column=0)
e1=Entry(win)
e1.grid(row=0,column=1)
l2=Label(win,text="password")
l2.grid(row=1,column=0)
e2=Entry(win,show="*")
e2.grid(row=1,column=1)
l3=Label(win,text="email")
l3.grid(row=2,column=0)
e3=Entry(win)
e3.grid(row=2,column=1)
l4=Label(win,text="mobile")
l4.grid(row=3,column=0)
e4=Entry(win)
e4.grid(row=3,column=1)
l5=Label(win,text="address")
l5.grid(row=4,column=0)
e5=Entry(win)
e5.grid(row=4,column=1)

def submit():
    name=e1.get()
    password=e2.get()
    email=e3.get()
    mobile=e4.get()
    address=e5.get()
    print("name",name)
    print("password",password)
    print("email",email)
    print("mobile",mobile)
    print("address",address)
    messagebox.showinfo("form","form submitted")

b1=Button(win,text="submit",command=submit)
b1.grid(row=5,column=1)
win.mainloop()
