# tkinter grid
import tkinter
win=tkinter.Tk()
win.title("first window")
win.geometry("200x200")
win.maxsize(400,400)
win.minsize(100,100)
win.config(bg="red")
def data():
    l4=tkinter.Label(win)
    l4.pack()
    data=e1.get()
    l4.config(text=data)
    print(data)
l1=tkinter.Label(win,text="name")
l2=tkinter.Label(win,text="password")
l3=tkinter.Label(win,text="email")    
l1.pack()
e1=tkinter.Entry(win)
e1.pack()
b1=tkinter.Button(win,text="click")
b1.pack()
c1=tkinter.Checkbutton(win,text="SSLC")
c1.pack()
win.mainloop()